### ISSUE TITLE
[AQ] Model Validation

### ISSUE THREAD

**Issue by tmc9031** [staruml/staruml-docs#5]
Where can I find detail about `Validation Result` errors info ???
And, I notice some `UML005` flag, is the `UML005` flag defined in UML standard ???
Now, I don't know how to solve these errors ...

Please give me some help, thanks

**Comment by niklauslee** [comment]
It means that there is a conflicted operation already existed on the inherited operations (from ancestors). You need to rename or change signature (parameters) the operation to avoid the error.

Actually, there is a problem on UML005 rule which don't allow operations from Interfaces. In recent release (v2.2.0), the operations from Interfaces are allowed to be redefined in implementing Classes.
